[package]
name = "internal_types"
version = "0.1.0"
authors = ["Andrew Lamb <andrew@nerdnetworks.org>"]
edition = "2018"
description = "InfluxDB IOx internal types, shared between IOx instances"
readme = "README.md"

[dependencies]
arrow = { version = "4.0", features = ["prettyprint"] }
snafu = "0.6"
observability_deps = { path = "../observability_deps" }

[dev-dependencies]
arrow_util = { path = "../arrow_util" }
