[package]
name = "datafusion_util"
version = "0.1.0"
authors = ["Andrew Lamb <andrew@nerdnetworks.org>"]
edition = "2018"
description = "Datafusion utilities"

[dependencies]

datafusion = { path = "../datafusion" }
futures = "0.3"
