[package]
name = "google_types"
version = "0.1.0"
authors = ["Raphael Taylor-Davies <r.taylordavies@googlemail.com>"]
description = "Standard Protobuf definitions - extracted into separate crate to workaround https://github.com/hyperium/tonic/issues/521"
edition = "2018"

[dependencies] # In alphabetical order
chrono = "0.4"
prost = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.44"

[build-dependencies] # In alphabetical order
prost-build = "0.7"
