[package]
name = "delorean_storage"
version = "0.1.0"
authors = ["alamb <andrew@nerdnetworks.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu = "0.6.2"
async-trait = "0.1"
tokio = { version = "0.2", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_urlencoded = "0.6.1"
tracing = "0.1"
croaring = "0.4.5"

delorean_arrow = { path = "../delorean_arrow" }
delorean_line_parser = { path = "../delorean_line_parser" }
delorean_data_types = { path = "../delorean_data_types" }
delorean_test_helpers = { path = "../delorean_test_helpers" }