[package]
name = "packers"
version = "0.1.0"
authors = ["Andrew Lamb <alamb@influxdata.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
snafu = "0.6.2"
tracing = "0.1"
rand = "0.7.3"
human_format = "1.0.3"

delorean_arrow = { path = "../delorean_arrow" }
data_types = { path = "../data_types" }
delorean_tsm = { path = "../delorean_tsm" }

[dev-dependencies]
delorean_test_helpers ={ path = "../delorean_test_helpers" }
