[package]
name = "delorean_write_buffer"
version = "0.1.0"
authors = ["alamb <andrew@nerdnetworks.org>"]
edition = "2018"

[dependencies]

delorean_arrow = { path = "../delorean_arrow" }
data_types = { path = "../data_types" }
delorean_generated_types = { path = "../delorean_generated_types" }
delorean_line_parser = { path = "../delorean_line_parser" }
delorean_storage = { path = "../delorean_storage" }
wal = { path = "../wal" }
delorean_test_helpers = { path = "../delorean_test_helpers" }

async-trait = "0.1"
chrono = "0.4"
flatbuffers = "0.6.1"
snafu = "0.6.2"
sqlparser = "0.6.1"
string-interner = "0.12.0"
tokio = { version = "0.2", features = ["full"] }
tracing = "0.1"

[dev-dependencies]
delorean_test_helpers = { path = "../delorean_test_helpers" }
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false
