[package]
name = "delorean"
version = "0.1.0"
authors = ["Paul Dix <paul@pauldix.net>"]
edition = "2018"
default-run = "delorean"

[workspace]
members = [
    "delorean_generated_types",
    "delorean_ingest",
    "delorean_line_parser",
    "delorean_object_store",
    "delorean_parquet",
    "delorean_partitioned_store",
    "delorean_table",
    "delorean_table_schema",
    "delorean_test_helpers",
    "delorean_tsm",
    "delorean_storage",
    "delorean_wal",
    "delorean_wal_writer",
    "delorean_write_buffer",
    "influxdb2_client",
]

[profile.release]
debug = true

[dependencies]
delorean_generated_types = { path = "delorean_generated_types" }
delorean_ingest = { path = "delorean_ingest" }
delorean_line_parser = { path = "delorean_line_parser" }
delorean_parquet = { path = "delorean_parquet" }
delorean_partitioned_store = { path = "delorean_partitioned_store" }
delorean_table = { path = "delorean_table" }
delorean_table_schema = { path = "delorean_table_schema" }
delorean_wal = { path = "delorean_wal" }
delorean_wal_writer = { path = "delorean_wal_writer" }
delorean_write_buffer = { path = "delorean_write_buffer" }
delorean_object_store = { path = "delorean_object_store" }
delorean_storage = { path = "delorean_storage" }
delorean_tsm = { path = "delorean_tsm" }

bytes = "0.5.4"
hyper = "0.13"
tokio = { version = "0.2", features = ["full"] }

clap = "2.33.1"
dotenv = "0.15.0"
dirs = "2.0.2"
env_logger = "0.7.1"
futures = "0.3.1"

serde_json = "1.0.44"
serde_urlencoded = "0.6.1"
serde = { version = "1.0", features = ["derive"] }
csv = "1.1"
byteorder = "1.3.4"

tonic = "0.2.0"
prost = "0.6.1"
prost-types = "0.6.1"
tracing = "0.1"
tracing-futures="0.2.4"

http = "0.2.0"
snafu = "0.6.2"
libflate = "1.0.0"
arrow = { git = "https://github.com/apache/arrow.git", rev = "62dfa114d6683172927fab40fa6c4ddabae8fef4"}


[dev-dependencies]
assert_cmd = "1.0.0"
criterion = "0.3"
delorean_test_helpers = { path = "delorean_test_helpers" }
hex = "0.4.2"
influxdb2_client = { path = "influxdb2_client" }
libflate = "1.0.0"
rand = "0.7.2"
reqwest = "0.10.1"
predicates = "1.0.4"
tempfile = "3.1.0"

[[bench]]
name = "encoders"
harness = false

[[bench]]
name = "line_parser"
harness = false

[[bench]]
name = "mapper"
harness = false

[[bench]]
name = "line_protocol_to_parquet"
harness = false

[[bench]]
name = "packers"
harness = false
