[package]
name = "delorean"
version = "0.1.0"
authors = ["Paul Dix <paul@pauldix.net>"]
edition = "2018"
default-run = "delorean"

[workspace]
members = [
    "delorean_ingest",
    "delorean_line_parser",
    "delorean_parquet",
    "delorean_table",
    "delorean_table_schema",
    "delorean_test_helpers",
    "delorean_generated_types",
    "delorean_utilities",
    "delorean_wal",
]

[profile.release]
debug = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
delorean_generated_types = { path = "delorean_generated_types" }
delorean_ingest = { path = "delorean_ingest" }
delorean_line_parser = { path = "delorean_line_parser" }
delorean_parquet = { path = "delorean_parquet" }
delorean_table = { path = "delorean_table" }
delorean_table_schema = { path = "delorean_table_schema" }
delorean_wal = { path = "delorean_wal" }

bytes = "0.5.4"
integer-encoding = "1.0.7"

hyper = "0.13"
tokio = { version = "0.2", features = ["full"] }

clap = "2.33.1"
dotenv = "0.15.0"
dirs = "2.0.2"
env_logger = "0.7.1"
log = "0.4.8"
futures = "0.3.1"

serde_json = "1.0.44"
serde = { version = "1.0", features = ["derive"] }
csv = "1.1"
byteorder = "1.2.1"

num_cpus = "1.11.1"

tonic = "0.2.0"
prost = "0.6.1"
prost-types = "0.6.1"

crc32fast = "1.2.0"
num = "0.2.1"

# using croaring here because we needed Treemap support for u64
# for series ids and we needed serialization, which the pure Rust
# crate didn't offer.
croaring = "0.4.2"
http = "0.2.0"
serde_urlencoded = "0.6.1"
snafu = "0.6.2"
either = "1.5.3"
flatbuffers = "0.6.1"
libflate = "1.0.0"

[dev-dependencies]
assert_cmd = "1.0.0"
chrono = "0.4"
criterion = "0.3"
delorean_test_helpers = { path = "delorean_test_helpers" }
hex = "0.4.2"
libflate = "1.0.0"
rand = "0.7.2"
reqwest = { version = "0.10.1", features = ["blocking"] }
predicates = "1.0.4"
tempfile = "3.1.0"

[[bench]]
name = "encoders"
harness = false

[[bench]]
name = "line_parser"
harness = false
