[package]
name = "delorean"
version = "0.1.0"
authors = ["Paul Dix <paul@pauldix.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.5.4"
integer-encoding = "1.0.7"

hyper = "0.13"
tokio = { version = "0.2", features = ["full"] }

dotenv = "0.15.0"
dirs = "2.0.2"
env_logger = "0.7.1"
log = "0.4.8"
futures = "0.3.1"

serde_json = "1.0.44"
serde = "1.0"
csv = "1.1"
rocksdb = "0.13"
byteorder = "1.3.4"

num_cpus = "1.11.1"

tonic = "0.1.1"
prost = "0.6.1"
prost-types = "0.6.1"

# using croaring here because we needed Treemap support for u64
# for series ids and we needed serialization, which the pure Rust
# crate didn't offer.
croaring = "0.4.2"
http = "0.2.0"
serde_urlencoded = "0.6.1"
nom = "5.1.1"

[dev-dependencies]
criterion = "0.3"
reqwest = { version = "0.10.1", features = ["blocking"] }
assert_cmd = "0.12.0"
rand = "0.7.2"
proptest = "0.9.5"

[[bench]]
name = "encoders"
harness = false

[build-dependencies]
tonic-build = "0.1.1"
rand = "0.7.2"
