[package]
name = "delorean_partitioned_store"
version = "0.1.0"
authors = ["alamb <andrew@nerdnetworks.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.1"
snafu = "0.6.2"
tracing = "0.1"
integer-encoding = "1.0.7"
num = "0.2.1"
tokio = { version = "0.2", features = ["full"] }
# using croaring here because we needed Treemap support for u64
# for series ids and we needed serialization, which the pure Rust
# crate didn't offer.
croaring = "0.4.5"
either = "1.5.3"
crc32fast = "1.2.0"
flatbuffers = "0.6.1"


delorean_generated_types = { path = "../delorean_generated_types" }
delorean_line_parser = { path = "../delorean_line_parser" }
delorean_storage = { path = "../delorean_storage" }
delorean_test_helpers = { path = "../delorean_test_helpers" }
delorean_tsm = { path = "../delorean_tsm" }
delorean_wal = { path = "../delorean_wal" }
delorean_wal_writer = { path = "../delorean_wal_writer" }
delorean_write_buffer = { path = "../delorean_write_buffer" }
