[package]
name = "parquet_file"
version = "0.1.0"
authors = ["Nga Tran <nga-tran@live.com>"]
edition = "2018"

[dependencies] # In alphabetical order
arrow_deps = { path = "../arrow_deps" }
bytes = "1.0"
data_types = { path = "../data_types" }
futures = "0.3.7"
internal_types = {path = "../internal_types"}
object_store = {path = "../object_store"}
parking_lot = "0.11.1"
snafu = "0.6"
tracker = { path = "../tracker" }
