[package]
name = "test_helpers"
version = "0.1.0"
authors = ["Paul Dix <paul@pauldix.net>"]
edition = "2018"

[dependencies] # In alphabetical order
dotenv = "0.15.0"
tempfile = "3.1.0"
tracing = "0.1"
tracing-subscriber = "0.2.15"
