[package]
name = "influxdb_iox_client"
version = "0.1.0"
authors = ["Dom Dwyer <dom@itsallbroken.com>"]
edition = "2018"

[features]
flight = ["arrow_deps", "serde/derive", "tonic", "serde_json", "futures-util"]

[dependencies]
# Workspace dependencies, in alphabetical order
arrow_deps = { path = "../arrow_deps", optional = true }
data_types = { path = "../data_types" }

# Crates.io dependencies, in alphabetical order
futures-util = { version = "0.3.1", optional = true }
reqwest = { version = "0.11.0", features = ["gzip", "json"] }
serde = "1.0.118"
serde_json = { version = "1.0.44", optional = true }
thiserror = "1.0.23"
tokio = { version = "1.0", features = ["macros"] }
tonic = { version = "0.4.0", optional = true }

[dev-dependencies] # In alphabetical order
rand = "0.8.1"
serde_json = "1.0"
