[package]
name = "influxdb_iox_client"
version = "0.1.0"
authors = ["Dom Dwyer <dom@itsallbroken.com>"]
edition = "2018"

[features]
flight = ["arrow", "arrow-flight", "serde/derive", "serde_json", "futures-util"]
format = ["arrow"]

[dependencies]
# Workspace dependencies, in alphabetical order
arrow = { version = "4.0", optional = true }
arrow-flight = { version = "4.0", optional = true}
generated_types = { path = "../generated_types" }

# Crates.io dependencies, in alphabetical order
futures-util = { version = "0.3.1", optional = true }
http = "0.2.3"
hyper = "0.14"
prost = "0.7"
serde = "1.0.118"
serde_json = { version = "1.0.44", optional = true }
thiserror = "1.0.23"
tokio = { version = "1.0", features = ["macros"] }
tonic = { version = "0.4.0" }

[dev-dependencies] # In alphabetical order
rand = "0.8.3"
serde_json = "1.0"
