[package]
name = "delorean_segment_store"
version = "0.1.0"
authors = ["Edd Robinson <me@edd.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
delorean_arrow = { path = "../delorean_arrow" }
delorean_table = { path = "../delorean_table" }
croaring = "0.4.5"

[dev-dependencies]
criterion = "0.3"