[package]
name = "delorean_test_helpers"
version = "0.1.0"
authors = ["Paul Dix <paul@pauldix.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
tempfile = "3.1.0"
env_logger = "0.7.1"
tracing = "0.1"
