[package]
name = "arrow_deps"
version = "0.1.0"
authors = ["Andrew Lamb <andrew@nerdnetworks.org>"]
edition = "2018"
description = "Apache Arrow / Parquet / DataFusion dependencies for InfluxDB IOx, to ensure consistent versions and unified updates"

[dependencies] # In alphabetical order
# We are using development version of arrow/parquet/datafusion and the dependencies are at the same rev

# The version can be found here: https://github.com/apache/arrow/commit/5ae63f8ec0c14d5e871aa79d90e5d163b369e704
#
arrow = { git = "https://github.com/apache/arrow.git", rev = "5ae63f8ec0c14d5e871aa79d90e5d163b369e704" , features = ["simd"] }
arrow-flight = { git = "https://github.com/apache/arrow.git", rev = "5ae63f8ec0c14d5e871aa79d90e5d163b369e704" }
datafusion = { git = "https://github.com/apache/arrow.git", rev = "5ae63f8ec0c14d5e871aa79d90e5d163b369e704" }
# Turn off the "arrow" feature; it currently has a bug that causes the crate to rebuild every time
# and we're not currently using it anyway
parquet = { git = "https://github.com/apache/arrow.git", rev = "5ae63f8ec0c14d5e871aa79d90e5d163b369e704", default-features = false, features = ["snap", "brotli", "flate2", "lz4", "zstd"] }
