[package]
name = "delorean_arrow"
version = "0.1.0"
authors = ["alamb <andrew@nerdnetworks.org>"]
edition = "2018"
description = "Apache Arrow / Parquet / DataFusion dependencies for delorean, to ensure consistent versions and unified updates"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# We are using development version of arrow/parquet/datafusion and the dependencies are at the same rev
# Check out the current rev @ https://github.com/apache/arrow/commit/171e8bfe5fe13467a1763227e495fae6bc5d011d

arrow = { git = "https://github.com/apache/arrow.git", rev = "171e8bfe5fe13467a1763227e495fae6bc5d011d"}
datafusion = { git = "https://github.com/apache/arrow.git", rev = "171e8bfe5fe13467a1763227e495fae6bc5d011d" }
# Turn off the "arrow" feature; it currently has a bug that causes the crate to rebuild every time
# and we're not currently using it anyway
parquet = { git = "https://github.com/apache/arrow.git", rev = "171e8bfe5fe13467a1763227e495fae6bc5d011d", default-features = false, features = ["snap", "brotli", "flate2", "lz4", "zstd"] }
