[package]
name = "delorean_arrow"
version = "0.1.0"
authors = ["alamb <andrew@nerdnetworks.org>"]
edition = "2018"
description = "Apache Arrow / Parquet / DataFusion dependencies for delorean, to ensure consistent versions and unified updates"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# We are using development version of arrow/parquet/datafusion and the dependencies are at the same rev

##### TEMP Pull in a branch from Andrew's fork that has the fix for ARROW-10136 on it


arrow = { git = "https://github.com/alamb/arrow.git", branch="alamb/arrow-upstream"}
datafusion = { git = "https://github.com/alamb/arrow.git", branch="alamb/arrow-upstream" }
parquet = { git = "https://github.com/alamb/arrow.git", branch="alamb/arrow-upstream", default-features = false, features = ["snap", "brotli", "flate2", "lz4", "zstd"] }


# TODO: uncomment the below and pick up arrow from the apache repo after fix for ARROW-10136 is merged
# Check out the current rev @ https://github.com/apache/arrow/commit/571d48e007718321bca8adb5f100555fed0e1957
#
#arrow = { git = "https://github.com/apache/arrow.git", rev = "571d48e007718321bca8adb5f100555fed0e1957"}
#datafusion = { git = "https://github.com/apache/arrow.git", rev = "571d48e007718321bca8adb5f100555fed0e1957" }
# Turn off the "arrow" feature; it currently has a bug that causes the crate to rebuild every time
# and we're not currently using it anyway
#parquet = { git = "https://github.com/apache/arrow.git", rev = "571d48e007718321bca8adb5f100555fed0e1957", default-features = false, features = ["snap", "brotli", "flate2", "lz4", "zstd"] }
