[package]
name = "delorean_mem_qe"
version = "0.1.0"
authors = ["Edd Robinson <me@edd.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
delorean_table = { path = "../delorean_table" }
arrow = { git = "https://github.com/alamb/arrow.git", rev="46f18c2602072e083809e0846b810e0cc3c59fdd", version = "2.0.0-SNAPSHOT" }
parquet = { git = "https://github.com/alamb/arrow.git", rev="46f18c2602072e083809e0846b810e0cc3c59fdd", version = "2.0.0-SNAPSHOT" }
datafusion = { git = "https://github.com/alamb/arrow.git", rev="46f18c2602072e083809e0846b810e0cc3c59fdd", version = "2.0.0-SNAPSHOT" }
#arrow = { path = "/Users/alamb/Software/arrow/rust/arrow" }
#parquet = { path = "/Users/alamb/Software/arrow/rust/parquet" }
#datafusion = { path = "/Users/alamb/Software/arrow/rust/datafusion" }
snafu = "0.6.8"
croaring = "0.4.5"
crossbeam = "0.7.3"
chrono = "0.4"
log = "0.4.11"
env_logger = "0.7.1"
human_format = "1.0.3"



[dev-dependencies]
