[package]
name = "generated_types"
version = "0.1.0"
authors = ["Paul Dix <paul@pauldix.net>"]
edition = "2018"

[dependencies] # In alphabetical order
flatbuffers = "0.6" # TODO: Update to 0.8
futures = "0.3.1"
prost = "0.7"
prost-types = "0.7"
tonic = "0.4"
tracing = "0.1"
google_types = { path = "../google_types" }

[build-dependencies] # In alphabetical order
tonic-build = "0.4"
prost-build = "0.7"
