[package]
name = "data_types"
version = "0.1.0"
authors = ["pauldix <paul@pauldix.net>"]
description = "InfluxDB IOx data_types, shared between IOx instances and IOx clients"
edition = "2018"
readme = "README.md"

[dependencies] # In alphabetical order
chrono = { version = "0.4", features = ["serde"] }
influxdb_line_protocol = { path = "../influxdb_line_protocol" }
percent-encoding = "2.1.0"
regex = "1.4"
serde = { version = "1.0", features = ["rc", "derive"] }
serde_regex = "1.1"
snafu = "0.6"
observability_deps = { path = "../observability_deps" }

[dev-dependencies] # In alphabetical order
test_helpers = { path = "../test_helpers" }
