[package]
name = "metrics"
version = "0.1.0"
authors = ["Edd Robinson <me@edd.io>"]
edition = "2018"

# This crate contains the application-specific abstraction of the metrics 
# implementation for IOx. Any crate that wants to expose telemetry should use 
# this crate. 


[dependencies] # In alphabetical order
observability_deps = { path = "../observability_deps" }
once_cell = { version = "1.4.0", features = ["parking_lot"] }
parking_lot = "0.11.1"

[dev-dependencies] # In alphabetical order

